[application]
name = "bae"

[bundle]
identifier = "com.bae.app"
publisher = "bae"

[bundle.macos]
bundle_name = "bae"

[web.app]

# HTML title tag content
title = "bae"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
